version: '3'

services:
  client:
    build: ./client
    container_name: client
    tty: true
    stdin_open: true
    volumes:
      - ./client/app:/client
    ports:
      - '5173:5173'
    command: sh -c "npm run dev"

  server:
    build: ./server
    container_name: server
    tty: true
    stdin_open: true
    volumes:
      - ./server/src:/server
    ports:
      - '8080:8080'
